# Generated by Django 6.1.1 on 2026-09-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, db_index=True, null=True)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=60)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('middle', "O'rta"), ('high', 'Yuqori')], default='beginner', max_length=16)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_profiles', to='universities.direction')),
                ('subjects', models.ManyToManyField(blank=True, related_name='onboarding_profiles', to='catalog.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_profile',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('days', models.JSONField(default=list)),
                ('weak_subject_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='onboarding.onboardingprofile')),
            ],
            options={
                'db_table': 'onboarding_plan',
                'ordering': ['-id'],
            },
        ),
    ]
