# Generated by Django 6.1.1 on 2026-10-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='return_path',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
