# Generated by Django 6.1.1 on 2026-09-29 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('practice', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='practiceanswer',
            index=models.Index(fields=['session', 'is_correct'], name='prac_answer_session_correct'),
        ),
        migrations.AddIndex(
            model_name='practiceanswer',
            index=models.Index(fields=['answered_at'], name='prac_answer_answered_at'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'started_at'], name='prac_session_user_started'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'finished_at'], name='prac_session_user_finished'),
        ),
    ]
