# Generated by Django 6.1.1 on 2026-09-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('practice', '0002_practicesession_deadline_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='catalog.subject'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=32, unique=True)),
                ('style', models.CharField(choices=[('international', 'Xalqaro'), ('local', 'Mahalliy')], max_length=16)),
                ('full_name', models.CharField(max_length=150)),
                ('score_percent', models.PositiveSmallIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=8)),
                ('passed', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='practice.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_certificate',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'style'), name='uniq_certificate_session_style')],
            },
        ),
    ]
