# Generated by Django 6.1.1 on 2026-09-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_practicesession_subject_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='practice.practicesession'),
        ),
    ]
