# Generated by Django 6.1.1 on 2026-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_certificate_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('finished', 'Yakunlangan'), ('abandoned', 'Tashlab ketilgan')], db_index=True, default='in_progress', max_length=20),
        ),
    ]
